### ISSUE TITLE
--cwd option confusing

### ISSUE THREAD

**Issue by gingermusketeer** [chrisdickinson/beefy#55]
The docs say that specifying --cwd will run beefy as though it was running from the specified directory. However i could not get it to work like that.

My directory structure is as follows

``` bash
- app
  - index.js
  - index.html
- node_modules
- package.json
```

if i run beefy from within the app directory i can use the following command
`../node_modules/.bin/beefy index.js -- -t brfs`
If i run it from the project root i need to use the following command
`./node_modules/.bin/beefy --cwd app app/index.js:index.js -- -t brfs`

My expectation is that i should be able to use the following command
`./node_modules/.bin/beefy --cwd app index.js -- -t brfs`

``` bash
$ node -v
v0.10.29
$ npm list beefy
└── beefy@2.0.3
```

**Comment by jessaustin** [comment]
AFAICT `--cwd` is about limiting file watches to relevant directories (i.e. not `node_modules/`) rather than how the file path is specified. It's actually quite valuable for avoiding `ENOSPC` as described in #89.
