### ISSUE TITLE
Push 2.1.2 to npm

### ISSUE THREAD

**Issue by wolframkriesing** [chrisdickinson/beefy#72]
Could you please push 2.1.2 to npm? 2.1.1 seems to be latest there https://www.npmjs.com/package/beefy
(I hope to get this issue fixed 2.1.2 https://github.com/sass/node-sass/issues/301 )
thanks in advance

**Comment by dlmanning** [comment]
woops, thanks for the reminder

**Comment by wolframkriesing** [comment]
thanks a lot
