### ISSUE TITLE
`live` causes trumpet error

### ISSUE THREAD

**Issue by jez0990** [chrisdickinson/beefy#75]
When I open the browser...

```
/home/jeremy/.npm-packages/lib/node_modules/beefy/node_modules/script-injector/node_modules/trumpet/index.js:87
            d.end();
              ^
TypeError: Object #<Object> has no method 'end'
    at /home/jeremy/.npm-packages/lib/node_modules/beefy/node_modules/script-injector/node_modules/trumpet/index.js:87:15
    at Array.forEach (native)
    at Trumpet.<anonymous> (/home/jeremy/.npm-packages/lib/node_modules/beefy/node_modules/script-injector/node_modules/trumpet/index.js:86:26)
    at Trumpet.g (events.js:180:16)
    at Trumpet.emit (events.js:92:17)
    at Plex.<anonymous> (/home/jeremy/.npm-packages/lib/node_modules/beefy/node_modules/script-injector/node_modules/trumpet/index.js:23:14)
    at Plex.g (events.js:180:16)
    at Plex.emit (events.js:117:20)
    at /home/jeremy/.npm-packages/lib/node_modules/beefy/node_modules/script-injector/node_modules/trumpet/node_modules/html-select/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:934:16
```

**Comment by noilly** [comment]
I had the same issue when using beefy to serve an Angular.js app using ngRoute. Accessing the route caused beefy to crash with an error just like this. Removing the --live flag resolved the issue.

**Comment by kjell** [comment]
Yep. Angular, ngRoute, `--live` causes the above error. The reason I'm using beefy is is because I want live reloads. I fixed the error by changing `…node_modules/beefy/node_modules/script-injector/node_modules/trumpet/index.js` line 86 from

```js
        duplex.splice(0).forEach(function (d) {
            d.end();
            d.resume();
        });
```

to 

```js
        duplex.splice(0).forEach(function (d) {
            if(d.end) d.end();
            if(d.resume) d.resume();
        });
```

I wrote a test script using `script-injector` to inject `console.log('injected')` into the same `index.html` and it worked OK:

```js
fs = require('fs')
si = require('script-injector')

fs.createReadStream('index.html')
  .pipe(si(function() { console.log('injected') }))
  .pipe(process.stdout)
```

So the problem must have something to do with beefy?

**Comment by dlmanning** [comment]
@kjell I started getting this error in script-injector when I updated the trumpet dependency recently. I'll try to track it down this weekend and get beefy's live-reload working again.

**Comment by cryptoquick** [comment]
Any progress on this issue? I'm also seeing this issue manifest itself within my console. :crying_cat_face:
