### ISSUE TITLE
Support for react and jsx

### ISSUE THREAD

**Issue by kevinsimper** [chrisdickinson/beefy#79]
It would be great if you could get jsx support out of the box, then beefy would be a quick tool to prototype react.js components.

**Comment by mattdesl** [comment]
Sounds very project specific. Not everybody uses React. :wink: 

You can do this:

```npm install babelify```

```beefy blah.js -- -t babelify```

**Comment by dlmanning** [comment]
Yeah, babelify browserify transform is the way to go for this.

**Comment by kevinsimper** [comment]
Ahh, yes of course.

It could be added to the Readme :)
