### ISSUE TITLE
Should Beefy be outputing a file?

### ISSUE THREAD

**Issue by NickGrease** [chrisdickinson/beefy#85]
Sorry bit of a beginner here, but when I run beefy from the cmd prompt:

    beefy index.js:bundle.js --live

Everything works as expected - but no file is actually output. The browser net panel shows the file is loaded from localhost:9966/bundle.js but the file doesn't exist in the base directory (where I launched the cmd prompt from and where the index.js is located) Output from the cmd prompt when I alter/save index.js, shows:

    /bundle.js ? C:\Users\[redacted]\AppData\Roaming\npm\node_modules\browserify .\index.js

Is all this normal? When I actually want the bundle.js file, am I supposed to just run browserify?

**Comment by chrisdickinson** [comment]
Yep – all is working as expected. Once you're ready to go to production, you can run your entry file (`index.js`) through browserify to get the bundle.

**Comment by NickGrease** [comment]
@chrisdickinson Thank you, I can stop pulling out what little hair I have left :) I think I went a little module crazy and forgot/misunderstood what did what. Great tool at any rate!
